version: '3'

services:
  agent:
    image: afj-0.4.2:latest

    container_name: 4294ef20-8305-4492-9c5c-2ed4bb68a695_Platform-admin
    restart: always
    environment:
      AFJ_REST_LOG_LEVEL: 1
    ports:
     - 9006:9006
     - 8006:8006
   
    volumes: 
      - ./agent-config/4294ef20-8305-4492-9c5c-2ed4bb68a695_Platform-admin.json:/config.json   
      
    command: --auto-accept-connections --config /config.json
      
volumes:
  pgdata:
  agent-indy_client:
  agent-tmp:
